#! /bin/bash

lsmod  | grep "brcmsmac\|b43\|ssb\|bcma\|wl\|brcmfmac\|cfg80211\|lib80211"
#rmmod brcmsmac
#rmmod ssb
#rmmod bcma
#rmmod b43
modprobe cfg80211
modprobe wl
lsmod  | grep "brcmsmac\|b43\|ssb\|bcma\|wl\|brcmfmac\|cfg80211\|lib80211"
