#! /bin/bash

if [ "" == "$1" ]; then
	echo "[ERROR] need 1 params! <github-clone path>"
	exit 1
fi

confpath="$1/linux_conf"
docpurepath="$1"

if [ ! -d "$confpath" ]; then
	echo "[ERROR] $conpath not exist!"
	exit 1
fi

function lnconf()
{
	if [[ "" == "$1" || "" == "$2" ]]; then
		return 1
	fi

	local src="$1"
	local dst="$2"

	if [[ -f $dst && ! -h $src ]]; then
		if [ -f $src ]; then
			echo "[INFO] bak '$src'"
			mv $src ${src}-bak
		fi
		echo "[INFO] $src -> $dst"
		ln -s $dst $src
	else
		echo "[WARN] '$dst' not found  or '$src' is a link file! '$src' not change."
	fi
}

#lnconf ~/.zshrc $confpath/.zshrc
lnconf ~/.zshrc $confpath/.zshrc-ohmyzsh
lnconf ~/.zprofile $confpath/.zprofile
lnconf ~/.zybshellrc $confpath/.zybshellrc
#lnconf ~/.bashrc $confpath/.bashrc
#lnconf ~/.bash_profile $confpath/.bash_profile
lnconf ~/.vimrc $confpath/.vimrc
lnconf ~/.xinitrc $confpath/.xinitrc
lnconf ~/.Xresources $confpath/.Xresources
lnconf ~/.config/herbstluftwm/autostart $confpath/autostart-herbstluftwm
lnconf ~/qs $docpurepath/qs

if [ 0 -eq 1 ]; then
	ln -s /home/zyb/d/git-warehouse/gows/ ~/gows
	ln -s /home/zyb/d/git-warehouse/gopath/ ~/gopath

	ln -s /home/zyb/d/git-warehouse/vimplugin/Vundle.vim ~/.vim/bundle/Vundle.vim
	ln -s /home/zyb/d/git-warehouse/vimplugin/colors/molokai/colors/molokai.vim ~/.vim/colors/molokai.vim
fi
